server:
  port: 0

spring:
  datasource:
    url:  jdbc:postgresql://localhost:5435/order_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  timelimiter:
    configs:
      default:
        timeout-duration: 3s